# Generated by Django 2.2.10 on 2020-08-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20200817_1536'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_to_Teacher',
            new_name='Students_to_Teachers',
        ),
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
        migrations.AddField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(through='school.Students_to_Teachers', to='school.Teacher'),
        ),
        migrations.AlterModelTable(
            name='students_to_teachers',
            table='students_to_teachers',
        ),
    ]
