# Generated by Django 2.2.10 on 2020-08-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20200817_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students_to_teachers',
            old_name='students',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='students_to_teachers',
            old_name='teachers',
            new_name='teacher',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='students',
            field=models.ManyToManyField(related_name='student', to='school.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='students_to_teachers',
            unique_together={('teacher', 'student')},
        ),
    ]
