# Generated by Django 2.2.10 on 2020-08-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_remove_teacher_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='students',
            field=models.ManyToManyField(related_name='students', to='school.Student'),
        ),
    ]
