# Generated by Django 2.2.10 on 2020-08-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_teacher_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(related_name='students', to='school.Teacher'),
        ),
        migrations.DeleteModel(
            name='Students_to_Teachers',
        ),
    ]
